"""Update email message

Revision ID: 5515d90e0a89
Revises: 6b9bb06296ec
Create Date: 2026-07-12 13:05:14.114470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5515d90e0a89'
down_revision: Union[str, Sequence[str], None] = '6b9bb06296ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('original_ai_subject', sa.String(), nullable=True))
    op.add_column('email_messages', sa.Column('original_ai_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'original_ai_body')
    op.drop_column('email_messages', 'original_ai_subject')
    # ### end Alembic commands ###
