"""Add provider metadata and attachments to email message

Revision ID: 5b365f460958
Revises: 5515d90e0a89
Create Date: 2026-07-12 13:12:49.443878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b365f460958'
down_revision: Union[str, Sequence[str], None] = '5515d90e0a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('provider_name', sa.String(), nullable=True))
    op.add_column('email_messages', sa.Column('provider_response', sa.JSON(), nullable=True))
    op.add_column('email_messages', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('email_messages', sa.Column('sent_by_user_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'sent_by_user_id')
    op.drop_column('email_messages', 'attachments')
    op.drop_column('email_messages', 'provider_response')
    op.drop_column('email_messages', 'provider_name')
    # ### end Alembic commands ###
