"""Add discovery fields

Revision ID: 6b9bb06296ec
Revises: 
Create Date: 2026-07-12 12:10:37.071512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9bb06296ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('google_place_id', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('business_status', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('discovery_source', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_google_place_id'), 'companies', ['google_place_id'], unique=True)
    op.add_column('orchestration_jobs', sa.Column('parent_job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orchestration_jobs', 'orchestration_jobs', ['parent_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orchestration_jobs', type_='foreignkey')
    op.drop_column('orchestration_jobs', 'parent_job_id')
    op.drop_index(op.f('ix_companies_google_place_id'), table_name='companies')
    op.drop_column('companies', 'discovery_source')
    op.drop_column('companies', 'discovered_at')
    op.drop_column('companies', 'longitude')
    op.drop_column('companies', 'latitude')
    op.drop_column('companies', 'business_status')
    op.drop_column('companies', 'review_count')
    op.drop_column('companies', 'rating')
    op.drop_column('companies', 'google_place_id')
    # ### end Alembic commands ###
