"""add opened_at and replied_at to email message

Revision ID: af05fac48522
Revises: 5b365f460958
Create Date: 2026-07-28 14:52:13.680942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af05fac48522'
down_revision: Union[str, Sequence[str], None] = '5b365f460958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_messages', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('email_messages', sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_messages', 'replied_at')
    op.drop_column('email_messages', 'opened_at')
    # ### end Alembic commands ###
